server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_d089f3ca6e8ac20?reconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: bf82ab67abfa2b
    password: cedaa35f

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# sql log
logging:
  level:
    com:
      andy:
        mapper: debug
