server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calendar?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lhb280214

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# sql log
logging:
  level:
    com:
      andy:
        mapper: debug
