server:
  port: 9999

#  postgres://namqekombkoegv:5d37def6de07800375db845772a9ba117ec1011fe5c35039a6eae4f4fd9984d0
#  @ec2-52-30-161-203.eu-west-1.compute.amazonaws.com:5432/d6sobh9oa22b24

#spring:
#  datasource:
#    url: jdbc:postgresql://ec2-52-30-161-203.eu-west-1.compute.amazonaws.com:5432/d6sobh9oa22b24?sslmode=require
#    driver-class-name: org.postgresql.Driver
#    username: namqekombkoegv
#    password: 5d37def6de07800375db845772a9ba117ec1011fe5c35039a6eae4f4fd9984d0

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_9d3c4a9194dd0a2?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: b8f2e8251d8316
    password: e20161ab
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/calendar?useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: lhb280214

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# sql log
logging:
  level:
    com:
      andy:
        mapper: debug
